[package]
name = "serde-rlp"
version = "0.1.0"
authors = ["Michał Papierski <michal@papierski.net>"]
include = [
    "**/*.rs",
    "Cargo.toml"
]

[dependencies]
byteorder = "1.2"
num = "0.2"
error = "0.1"
serde = "1.0.0"

[dev-dependencies]
serde_derive = "1.0.0"